version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--experimental.localPlugins.correlation.moduleName=github.com/saman-jafari/correlation-id-traefik"
#      - "--experimental.plugins.correlation.moduleName=github.com/saman-jafari/correlation-id-traefik"
#      - "--experimental.plugins.correlation.version=v0.2.0"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.middlewares=correlation@docker" # you can use this for global middleware activation on web
      - "--entrypoints.websecure.http.middlewares=correlation@docker" # you can use this for global middleware activation on websecure
    ports:
      - "80:80"
      - "8080:8080"
#    labels:
#      - "traefik.http.middlewares.correlation.plugin.correlation.headerName=x-correlation-id"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./:/plugins-local/src/github.com/saman-jafari/correlation-id-traefik/"


  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.middlewares.correlation.plugin.correlation.headerName=x-correlation-id"
#     - "traefik.http.routers.whoami.middlewares=correlation@docker" # you can use this for service middleware activation